# Default config for EnvGS
runner_cfg:
    visualizer_cfg:
        types: ['RENDER', 'DEPTH', 'ALPHA', 'NORMAL', 'SURFACE_NORMAL',
                'SPECULAR', 'DIFFUSE', 'REFLECTION']
    optimizer_cfg:
        lr: 0.05 # add default lr to params of other modules
        eps: 1.e-15
        lr_table:
            _xyz: 0.00016
            _features_dc: 0.0025
            _features_rest: 0.000125
            _opacity: 0.05
            _scaling: 0.005
            _rotation: 0.001
            _specular: 0.01
    scheduler_cfg:
        type: NoopLR
    epochs: 120
    ep_iter: 500
    save_latest_ep: 10
    save_ep: 120
    eval_ep: 10
    log_interval: 1
    record_images_to_tb: False # save disk space

model_cfg:
    chunkify_rays: False # for now, no ray chunking for Gaussian
    let_user_handle_input: True # let the user handle the output and input
    network_cfg:
        type: NoopNetwork # no network for this
        _delete_: True
    renderer_cfg:
        type: NoopRenderer
    sampler_cfg:
        type: EnvGSSampler
        xyz_lr_scheduler: # same as the 2DGS code
            lr_init: 0.00016
            lr_final: 0.0000016
            lr_delay_mult: 0.01
            max_steps: 30000
        # Reflection
        render_reflection: True
        render_reflection_start_iter: 6000
        # Base Gaussian
        sh_deg: 3
        sh_start_iter: 10000
        specular_channels: 1
        densify_until_iter: 21000
        normal_prop_until_iter: 18000
        color_sabotage_until_iter: 18000
        init_specular: 0.1 # important
        prune_visibility: True
        min_weight_threshold: null # turn this off
        # Environment Gaussian
        use_optix_tracing: True
        acc_filtering_start_iter: 30000
        specular_filtering_start_iter: -1 # do not use this
        env_sh_deg: 3
        env_sh_start_iter: 10000
        env_densify_until_iter: 42000
        env_densification_interval: 500
        env_opacity_reset_interval: 3000 # don't modify this
        env_densify_grad_threshold: 0.0001
        env_prune_visibility: True
        env_min_weight_threshold: 0.1
    supervisor_cfg:
        supervisor_cfgs:
            - type: VolumetricVideoSupervisor
            - type: EnvGSSupervisor
        img_loss_type: L1
        img_loss_weight: 0.8
        ssim_loss_weight: 0.2
        gs_dist_loss_weight: 0.0 # do not use this
        gs_norm_loss_weight: 0.04
        gs_norm_loss_start_iter: 4000
        use_acc_scale_gs_norm_loss: True
        use_dpt_scale_gs_norm_loss: False
        norm_loss_weight: 0.01 # use monocular normal prior
        norm_loss_start_iter: 4000
        use_acc_scale_norm_loss: True
        use_dpt_scale_norm_loss: False
        # perc_loss_weight: 0.01 # use perceptual loss

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg
        n_rays: -1
        use_normals: True # use monocular normal prior
    batch_sampler_cfg: &batch_sampler_cfg
        type: BatchSampler
        batch_size: 1

val_dataloader_cfg: # we see the term "dataloader" a one word?
    <<: *dataloader_cfg
    dataset_cfg:
        <<: *dataset_cfg
        use_normals: False
    batch_sampler_cfg:
        <<: *batch_sampler_cfg
