configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/envgs_synth.yaml # 2dgs model configuration
    - configs/datasets/shiny_blender/helmet.yaml # dataset usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
